Program ClassComp (output);

Uses CRT;

Begin
  Clrscr;
  WriteLn ('   -Computers in the school-');
  writeln ;
  Write ('Chemistry       ');
  WriteLn (4);
  Write ('Physics         ');
  WriteLn (8);
  Write ('Music           ');
  WriteLn (2);
  Write ('Math Lab        ');
  Writeln (12);
  Writeln;
  Write ('The total number of computers is ');
  Writeln (4+8+2+12);
  WriteLn;
  WriteLn ('Press the Enter key to continue..');
  Readln;
End.
